apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: fylo-data-storage-component-app
    newName: fylo-data-storage-component-app
    newTag: latest
